seed: 42
splits: [0.7,0.1,0.2] # train, val, test
mask_thres: 0.01
data_path: ./data/fake_TGC_0.041_pruned.h5

fp32:
  save_path: ./fp32
  model:
    masking: true
  train:
    epochs: 8128 # (2^7-1)*64
    mse_thres: 4
    cdr_args:
      initial_learning_rate: 3.e-3
      first_decay_steps: 64
      t_mul: 2.0
      m_mul: 0.7
      alpha: 0.2e-3
    bsz: 16384


fhq:
  save_path: ./213_output
  train:
    epochs: 8128 # (2^7-1)*64
    mse_thres: 5
    cdr_args:
      initial_learning_rate: 3.e-3
      first_decay_steps: 64
      t_mul: 2.0
      m_mul: 0.7
      alpha: 1.e-6
    bsz: 16384
  model:
    bops_reg_factor: 4.e-5
    l1_cc: 2.e-6
    l1_dc: 2.e-6
    l1_act: 2.e-6
    init_bw_a: 4
    init_bw_k: 4
    masking: true
  syn:
    bias_accum: 2
