seed: 42
data_path: 'data/inp_data.zst'
save_path: '72_u_output'

model:
  beta: 0
  a_bw_l1_reg: 0.5e-2
  w_bw_l1_reg: 2.e-2
  w_init_bw: 2
  a_init_bw: 2
  uniform: True

train:
  lr: 5.e-3
  bsz: 33200
  epochs: 1000
  val_split: 0.15
  acc_thres: 0.723
