seed: 42
data_path: 'data/inp_data.zst'
save_path: './72_output'

model:
  bops_reg_factor: 5.5e-5
  a_bw_l1_reg: 0.000002
  w_bw_l1_reg: 0.000002
  w_init_bw: 2
  a_init_bw: 2

train:
  lr: 0.005
  bsz: 33200
  epochs: 800
  val_split: 0.15
  acc_thres: 0.72
  
