seed: 42
data_path: 'data/inp_data.zst'
save_path: './763_output'

model:
  beta: 0.21e-5
  a_bw_l1_reg: 2.e-6
  w_bw_l1_reg: 2.e-6
  w_init_bw: 2
  a_init_bw: 2

train:
  lr: 0.005
  bsz: 33200
  epochs: 5000
  val_split: 0.15
  acc_thres: 0.763
