seed: 42
data_path: 'data/inp_data.zst'
save_path: '/tmp/jet_classifier_const2'

model:
  a_bw_l1_reg: 0.000002
  w_bw_l1_reg: 0.000002
  w_init_bw: 2
  a_init_bw: 2
  uniform: false
  n_hidden_layers: 3

beta:
  intervals:
    - epochs: 0
      betas: [6.e-5,6.e-5]
      interpolation: linear

train:
  bsz: 33200
  epochs: 5000
  val_split: 0.15
  calibrated_bops: false
  cdr_args:
    initial_learning_rate: 5.e-3
    first_decay_steps: 5000
    t_mul: 1
    m_mul: 0.98
    alpha: 1.e-6 
