seed: 42
data_path: "data/inp_data.zst"
save_path: "/tmp/jet_classifier_sweep_uauw"

model:
  a_bw_l1_reg: 0.000002
  w_bw_l1_reg: 0.000002
  w_init_bw: 2
  a_init_bw: 2
  uniform_a: true
  uniform_w: true
  n_hidden_layers: 3
  scale: 1.0

beta:
  intervals:
    - epochs: 0
      betas: [5.e-7, 5.e-7]
      interpolation: linear
    - epochs: 5000
      betas: [1.e-6, 2.e-3]
      interpolation: log

train:
  bsz: 33200
  epochs: 300000
  val_split: 0.15
  calibrated_bops: false
  cdr_args:
    initial_learning_rate: 5.e-3
    first_decay_steps: 2500
    t_mul: 1
    m_mul: 0.98
    alpha: 1.e-6
