seed: 42
data_path: 'data/inp_data.zst'
save_path: '/tmp/jet_classifier_sweep'

model:
  a_bw_l1_reg: 0.000002
  w_bw_l1_reg: 0.000002
  w_init_bw: 2
  a_init_bw: 2
  uniform: false

beta:
  intervals:
    - epochs: 0
      betas: [0,0]
      interpolation: linear
    - epochs: 5000
      betas: [1.e-6, 2.e-4]
      interpolation: log

train:
  lr: 0.005
  bsz: 33200
  epochs: 100000
  val_split: 0.15
  calibrated_bops: false
  
