seed: 42
data_path: 'data/inp_data.zst'
save_path: '/tmp/jet_classifier_sweep'

model:
  a_bw_l1_reg: 0.000002
  w_bw_l1_reg: 0.000002
  w_init_bw: 2
  a_init_bw: 2
  uniform: false
  n_hidden_layers: 3

beta:
  intervals:
    - epochs: 0
      betas: [3.e-7,3.e-7]
      interpolation: linear
    - epochs: 5000
      betas: [1.e-6, 5.e-3]
      interpolation: log

train:
  lr: 0.005
  bsz: 33200
  epochs: 300000
  val_split: 0.15
  calibrated_bops: false
  
