seed: 42
datapath: "/data/massive1/fastml_data/jet150"
val_split: 0.1
n_constituents: 64
pt_eta_phi: True

save_path: /tmp/jet_classifier_large_64-3
model:
  init_bw_a: 9
  init_bw_k: 6
  k_bw_l1_reg: 5.e-7
  a_bw_l1_reg: 5.e-7
train:
  lr: 0
  bsz: 512
  epochs: 5000
  cdr_args:
    initial_learning_rate: 5.e-3
    first_decay_steps: 50
    t_mul: 1.0 # fixed, cannot be changed here
    m_mul: 0.93
    alpha: 5.e-6
    alpha_steps: 5 # #epoch at lowest lr before next restart. Total cycle = first_decay_steps - alpha_steps
beta:
  intervals:
    - epochs: 0
      betas: [0.2e-7, 3.e-7]
      interpolation: linear
    - epochs: 500
      betas: [3.e-7, 3.e-5]
      interpolation: log
