seed: 42
datapath: ./data
val_split: 0.1


save_path: /tmp/svhn_sweep
model:
  init_bw_a: 6
  init_bw_k: 6
  parallel_factors: [1,1,1]
  k_bw_l1_reg_conv: 2.e-6
  k_bw_l1_reg_dense: 2.e-6
  a_bw_l1_reg: 2.e-6
train:
  lr: 0
  bsz: 2048
  epochs: 12000
  cdr_args:
    initial_learning_rate: 1.e-3
    first_decay_steps: 100
    t_mul: 1.0 # fixed, cannot be changed here
    m_mul: 0.96
    alpha: 1.e-6
    alpha_steps: 15 # #epoch at lowest lr before next restart. Total cycle = first_decay_steps - alpha_steps
beta:
  intervals:
    - epochs: 0
      betas: [0,0]
      interpolation: linear
    - epochs: 400
      betas: [0.8e-6, 5.e-5]
      interpolation: log
